<?php

/**
 * Test class for Skaya_Model_Service_Abstract.
 * Generated by PHPUnit on 2011-05-21 at 20:07:07.
 */
class Skaya_Model_Service_AbstractTest extends PHPUnit_Framework_TestCase {
	/**
	 * @var Skaya_Model_Service_Abstract
	 */
	protected $_service;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->_service = Skaya_Model_Service_Abstract::factory('Test');
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
	}

	/**
	 * @todo Implement testFactory().
	 */
	public function testFactory() {
		$this->assertInstanceOf('Service_Test', $this->_service);
		$this->assertInstanceOf('Service_Test', Skaya_Model_Service_Abstract::factory('Test'));
	}
}

class Service_Test extends Skaya_Model_Service_Abstract {

	public static function create($data = array()) {
		if (array_key_exists('id', $data)) {
			unset($data['id']);
		}
		return new TestModel($data);
	}

}