<?php

/**
 * Test class for Skaya_Model_Mapper_Decorator_Cache.
 * Generated by PHPUnit on 2011-05-22 at 00:28:39.
 */
class Skaya_Model_Mapper_Decorator_CacheTest extends PHPUnit_Framework_TestCase {
	/**
	 * @var Skaya_Model_Mapper_Decorator_Cache
	 */
	protected $_decorator;

	/**
	 * @var MyApp_Mapper_Test_User
	 */
	protected $_mapper;

	/**
	 * @var Zend_Cache_Core
	 */
	protected $_cache;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->_cache = Zend_Registry::get('cache');

		Skaya_Model_Mapper_MapperBroker::addPath(realpath(TESTS_PATH . '/Model/mappers/_files/mappers/'), 'MyApp');
		$broker = Skaya_Model_Mapper_MapperBroker::getInstance();
		$this->_mapper = $broker->getMapper('DbCache', 'Db');
		$this->_decorator = new Skaya_Model_Mapper_Decorator_Cache($this->_mapper);

		$this->_decorator->setCache($this->_cache);
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		$this->_cache->clean();
	}

	public function testType() {
		$this->assertInstanceOf('Skaya_Model_Mapper_Decorator_Cache', $this->_decorator);
	}

	/**
	 * @todo Implement testSetCache().
	 */
	public function testGetSetCache() {
		$this->assertInstanceOf('Zend_Cache_Core', $this->_decorator->getCache());
	}

	/**
	 * @todo Implement testSave().
	 */
	public function testSave() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testDelete().
	 */
	public function testDelete() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement test__call().
	 */
	public function testMagicCall() {
		$items = $this->_decorator->getItemsList();
	}

	/**
	 * @todo Implement testGetCacheId().
	 */
	public function testGetCacheId() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetCacheTags().
	 */
	public function testGetCacheTags() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}
}

?>
